### PR TITLE
Homework 14

### PR DESCRIPTION
**Pull request by CyberSergo**
Fill in all fields in the form using the Cypress framework

### CODE REVIEW

**Review by PollySt — COMMENTED** [review]
hey) your HW is very good. The one thing: best practice is to set page link as environment variable "baseUrl" in cypress.json. Then you can pass to cy.visit only endpoint

**Comment by CyberSergo** [comment]
@PollySt totally agree with you about the "baseURL" variable, this is indeed the correct solution. I didn't use this in my homework because at first, I didn't understand what our homework would look like, that all the code for all the work would be in one folder. Thanks for the feedback and advice, it's very helpful for me =)

**Comment by Volodymyr2211** [comment]
Hello.
You have done a good job. I have found a few inconsistencies:
The "it('Clicking on the "Submit" button.'," is not a test, because there are not any checks. 
Also, The 'Checking the correctness of all data' test is dependent on the previous tests. A best practice is to write 
independent tests.
Thanks for your attention.

**Comment by landriiuk** [comment]
lesson 14 comments

i saw u fix    cy.visit(MAIN_URL); at lesson 15
i've got a few spelling issue, pls fix it 
Screenshot 2022-02-15 at 14 04 04
Screenshot folder should be at .gitignore file

Your code working correctly
score 9/10

**Pull request merged**
